### PR TITLE
CloudFormation ES template.

### PR DESCRIPTION
**Pull request by corpulent**
CloudFormation ES template.

### CODE REVIEW

**Comment by nickwynja** [comment]
Also, does this need to be at the `aws/aws-cf-templates` path? Could we move it into `deploy-aws` or move the `deploy-aws` stuff into this `aws` directory?

**Comment by corpulent** [comment]
@nickwynja this template was used to setup the ElasticSearch cluster for IDS.  We use this same template to update the cluster, its not manual anymore, we just pass instructions to AWS.  AWS takes care of the EC2 instances and the index being available for the ones that are there tho.  I just need to save this template somewhere.

**Comment by clepore** [comment]
So is this good to be merged then?

**Comment by nickwynja** [comment]
@clepore Not yet. I'd like to consolidate these directories:

image

@corpulent is that something you're OK with?

**Comment by clepore** [comment]
@nickwynja, @corpulent said we should discuss the folder consolidation.

In the meantime we already merged in the fix to re-enable deploying documentation.

**Pull request merged**
